63 user profiles display stats such as wins and losses
0xEDU/ft_transcendence pull request #101
Opened 2024-03-07 21:30 UTC by rodsmade

### DONE
- user fixture (incomplete - Fer will improve this)
- create new match via post
- update match (scores really) via put
- implemented some stats (match_duration, ball_traveled_distance_cm, paddle_hits)
- profile stats updated from DB (not hardcoded anymore)

### TO GO:
- stats: classic_victories, coop_companions, classic_oponents

2024-03-07 21:39 UTC, 0xEDU requested changes

2024-03-07 21:39 UTC, 0xEDU commented on static/js/pong.js
> +	// let seconds = 3; // Initial value for the countdown
Faltou voltar pra 3 :sweat_smile:

2024-03-08 12:24 UTC, rodsmade commented on static/js/pong.js
> +	// let seconds = 3; // Initial value for the countdown
mano não sei usar essa interface de review do github 😭  subi alteração mas não parece que isso respondeu ao seu change request

2024-03-08 14:22 UTC, 0xEDU approved these changes

2024-03-08 14:23 UTC, merged